<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ulBOaok' shared service.

return $this->privates['.service_locator.ulBOaok'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'figureRepository' => ['privates', 'App\\Repository\\FigureRepository', 'getFigureRepositoryService.php', true],
    'fileUp' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService.php', true],
    'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService.php', true],
    'videoRepository' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService.php', true],
]);
