<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.huHR.Do' shared service.

return $this->privates['.service_locator.huHR.Do'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService.php', true],
    'figureRepository' => ['privates', 'App\\Repository\\FigureRepository', 'getFigureRepositoryService.php', true],
    'fileUp' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService.php', true],
    'post' => ['privates', '.errored..service_locator.huHR.Do.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.huHR.Do": it references class "App\\Entity\\Post" but no such service exists.'],
    'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService.php', true],
    'videoRepository' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService.php', true],
]);
