<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\FigureController::deleteImg' => ['privates', '.service_locator.meBJUHU', 'get_ServiceLocator_MeBJUHUService.php', true],
    'App\\Controller\\FigureController::updateImg' => ['privates', '.service_locator.9yLvjYR', 'get_ServiceLocator_9yLvjYRService.php', true],
    'App\\Controller\\PostController::creatPost' => ['privates', '.service_locator.ulBOaok', 'get_ServiceLocator_UlBOaokService.php', true],
    'App\\Controller\\PostController::deleteImgPost' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController::deletePost' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController::home' => ['privates', '.service_locator.CQwjxtm', 'get_ServiceLocator_CQwjxtmService.php', true],
    'App\\Controller\\PostController::post' => ['privates', '.service_locator.fLko.rf', 'get_ServiceLocator_FLko_RfService.php', true],
    'App\\Controller\\PostController::updatePost' => ['privates', '.service_locator.huHR.Do', 'get_ServiceLocator_HuHR_DoService.php', true],
    'App\\Controller\\SecurityController::forgot' => ['privates', '.service_locator.e0npJBJ', 'get_ServiceLocator_E0npJBJService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::updatePass' => ['privates', '.service_locator.kvRz10W', 'get_ServiceLocator_KvRz10WService.php', true],
    'App\\Controller\\UserController::ConfirmMailRegister' => ['privates', '.service_locator.Bg.EX6Q', 'get_ServiceLocator_Bg_EX6QService.php', true],
    'App\\Controller\\UserController::deleteUser' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::password' => ['privates', '.service_locator.kvRz10W', 'get_ServiceLocator_KvRz10WService.php', true],
    'App\\Controller\\UserController::profil' => ['privates', '.service_locator.jBUFzF2', 'get_ServiceLocator_JBUFzF2Service.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.K_H62a_', 'get_ServiceLocator_KH62aService.php', true],
    'App\\Controller\\VideoController::deleteVid' => ['privates', '.service_locator.XxOaJfn', 'get_ServiceLocator_XxOaJfnService.php', true],
    'App\\Controller\\VideoController::updateVideo' => ['privates', '.service_locator.N747g0D', 'get_ServiceLocator_N747g0DService.php', true],
    'App\\Controller\\FigureController:deleteImg' => ['privates', '.service_locator.meBJUHU', 'get_ServiceLocator_MeBJUHUService.php', true],
    'App\\Controller\\FigureController:updateImg' => ['privates', '.service_locator.9yLvjYR', 'get_ServiceLocator_9yLvjYRService.php', true],
    'App\\Controller\\PostController:creatPost' => ['privates', '.service_locator.ulBOaok', 'get_ServiceLocator_UlBOaokService.php', true],
    'App\\Controller\\PostController:deleteImgPost' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController:deletePost' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController:home' => ['privates', '.service_locator.CQwjxtm', 'get_ServiceLocator_CQwjxtmService.php', true],
    'App\\Controller\\PostController:post' => ['privates', '.service_locator.fLko.rf', 'get_ServiceLocator_FLko_RfService.php', true],
    'App\\Controller\\PostController:updatePost' => ['privates', '.service_locator.huHR.Do', 'get_ServiceLocator_HuHR_DoService.php', true],
    'App\\Controller\\SecurityController:forgot' => ['privates', '.service_locator.e0npJBJ', 'get_ServiceLocator_E0npJBJService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:updatePass' => ['privates', '.service_locator.kvRz10W', 'get_ServiceLocator_KvRz10WService.php', true],
    'App\\Controller\\UserController:ConfirmMailRegister' => ['privates', '.service_locator.Bg.EX6Q', 'get_ServiceLocator_Bg_EX6QService.php', true],
    'App\\Controller\\UserController:deleteUser' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:password' => ['privates', '.service_locator.kvRz10W', 'get_ServiceLocator_KvRz10WService.php', true],
    'App\\Controller\\UserController:profil' => ['privates', '.service_locator.jBUFzF2', 'get_ServiceLocator_JBUFzF2Service.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.K_H62a_', 'get_ServiceLocator_KH62aService.php', true],
    'App\\Controller\\VideoController:deleteVid' => ['privates', '.service_locator.XxOaJfn', 'get_ServiceLocator_XxOaJfnService.php', true],
    'App\\Controller\\VideoController:updateVideo' => ['privates', '.service_locator.N747g0D', 'get_ServiceLocator_N747g0DService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
