<?php


    namespace App\Tests\src\Entity;


    use App\Entity\Comment;
    use PHPUnit\Framework\TestCase;

    class CommentTest extends TestCase
    {
        private $comment;

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->comment = new Comment();
            $this->hydrate($this->comment);
        }

        public function hydrate($Com)
        {
            $this->comment->setContent('micfref');
            $this->comment->setName('gegerg');
            $this->comment->setDate(new \DateTime());
            $this->comment->setPhotoUser('lol.jpg');
        }

        public function testNameType()
        {
            $this->assertIsString($this->comment->getName());
        }

        public function testName()
        {
            $this->assertEquals('gegerg',$this->comment->getName());
        }

        public function testContent()
        {
            $this->assertEquals('micfref',$this->comment->getContent());
        }

        public function testContentType()
        {
            $this->assertIsString($this->comment->getContent());
        }

        public function testDate()
        {
            $this->assertInstanceOf(\DateTime::class,$this->comment->getDate());
        }

        public function testId()
        {
            $this->assertEquals(null,$this->comment->getID());
        }

        public function testPhotoType()
        {
            $this->assertIsString($this->comment->getPhotoUser());
        }

        public function testPhoto()
        {
            $this->assertEquals('lol.jpg',$this->comment->getPhotoUser());
        }

        public function testIdDetail()
        {
            $this->assertEquals(null,$this->comment->getDetail());
        }

        public function testIdUser()
        {
            $this->assertEquals(null,$this->comment->getUser());
        }

    }