<?php


    namespace App\Tests\src\Entity;


    use App\Entity\Comment;
    use PHPUnit\Framework\TestCase;

    class CommentTest extends TestCase
    {
        private $comment;

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->comment = new Comment();
            $this->hydrate($this->comment);
        }

        public function hydrate($com)
        {
            $this->comment->setContent('micfref');
            $this->comment->setCreatDate(new \DateTime());
        }

        public function testContent()
        {
            $this->assertEquals('micfref',$this->comment->getContent());
        }

        public function testContentType()
        {
            $this->assertIsString($this->comment->getContent());
        }

        public function testDate()
        {
            $this->assertInstanceOf(\DateTime::class,$this->comment->getCreatDate());
        }

        public function testId()
        {
            $this->assertEquals(null,$this->comment->getID());
        }

        public function testIdUser()
        {
            $this->assertEquals(null,$this->comment->getUser());
        }

        public function testIdFigure()
        {
            $this->assertEquals(null,$this->comment->getFigure());
        }

    }