<?php


    namespace App\Tests\src\Entity;



    use App\Entity\Figure;
    use PHPUnit\Framework\TestCase;

    class FigureTest extends TestCase
    {
        private $figure;

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->figure = new Figure();
            $this->hydrate($this->figure);
        }

        public function hydrate($figure)
        {
            $this->figure->setName('gegerg');
        }

        public function testName()
        {
            $this->assertEquals('gegerg',$this->figure->getName());
        }

        public function testNameType()
        {
            $this->assertIsString($this->figure->getName());
        }

        public function testId()
        {
            $this->assertEquals(null,$this->figure->getId());
        }

        public function testDetail()
        {
            $this->assertEquals(null,$this->figure->getDetail());
        }
    }