<?php


    namespace App\Tests\src\Entity;



    use App\Entity\Figure;
    use PHPUnit\Framework\TestCase;

    class FigureTest extends TestCase
    {
        private $figure;

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->figure = new Figure();
            $this->hydrate($this->figure);
        }

        public function hydrate($figure)
        {
            $this->figure->setNameFigure('gegerg');
            $this->figure->setCreatDate(new \DateTime());
            $this->figure->setContent('lol');
            $this->figure->setImgFigure('lol');
        }

        public function testNameFigure()
        {
            $this->assertEquals('gegerg',$this->figure->getNameFigure());
        }

        public function testNameFigureType()
        {
            $this->assertIsString($this->figure->getNameFigure());
        }

        public function testId()
        {
            $this->assertEquals(null,$this->figure->getId());
        }

        public function testDate()
        {
            $this->assertInstanceOf(\DateTime::class,$this->figure->getCreatDate());
        }

        public function testContent()
        {
            $this->assertEquals('lol',$this->figure->getContent());
        }

        public function testContentType()
        {
            $this->assertIsString($this->figure->getContent());
        }

        public function testImgFigure()
        {
            $this->assertEquals('lol',$this->figure->getImgFigure());
        }

        public function testImgFigureType()
        {
            $this->assertIsString($this->figure->getImgFigure());
        }

        public function testIdGroupNumber()
        {
            $this->assertEquals(null,$this->figure->getGroupNumber());
        }
    }