<?php


    namespace App\Tests\src\Entity;


    use App\Entity\Detail;
    use App\Entity\Img;
    use PHPUnit\Framework\TestCase;

    class ImgTest extends TestCase
    {
        private $img;

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->img = new Img();
            $this->hydrate($this->img);
        }

        public function hydrate($img)
        {
            $this->img->setNameImg('default');
        }

        public function testNameImg()
        {
            $this->assertEquals('default',$this->img->getNameImg());
        }

        public function testNameType()
        {
            $this->assertIsString($this->img->getNameImg());
        }

        public function testIdFigures()
        {
            $this->assertEquals(null,$this->img->getFigures());
        }

    }