<?php


    namespace App\Tests\src\Entity;

    use App\Entity\User;
    use PHPUnit\Framework\TestCase;

    class UserTest extends TestCase
    {
        private $user;

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->user = new User();
            $this->hydrate($this->user);
        }

        public function hydrate($user)
        {
            $this->user->setFirstName('mic');
            $this->user->setConfirmRegister('1');
            $this->user->setToken('1');
            $this->user->setEmail('lol@lol.moid');
            $this->user->setPassword('lol');
            $this->user->setImg('azert');
        }

        public function testFirstName()
        {
            $this->assertEquals('mic',$this->user->getFirstName());
        }

        public function testFirstNameType()
        {
            $this->assertIsString($this->user->getFirstName());
        }

        public function testConfirmRegister()
        {
            $this->assertEquals('1',$this->user->getConfirmRegister());
        }

        public function testToken()
        {
            $this->assertEquals('1',$this->user->getToken());
        }

        public function testMailType()
        {
            $this->assertIsString($this->user->getEmail());
        }

        public function testMail()
        {
            $this->assertEquals('lol@lol.moid',$this->user->getEmail());
        }

        public function testFailFirstName()
        {
            $this->assertIsNotInt($this->user->getFirstName());
        }

        public function testId()
        {
            $this->assertEquals(null,$this->user->getID());
        }

        public function testPassword()
        {
            $this->assertEquals('lol',$this->user->getPassword());
        }

        public function testImg()
        {
            $this->assertEquals('azert',$this->user->getImg());
        }

    }