<?php


    namespace App\Tests\src\Entity;

    use App\Entity\User;
    use PHPUnit\Framework\TestCase;

    class UserTest extends TestCase
    {
        private $user;

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->user = new User();
            $this->hydrate($this->user);
        }

        public function hydrate($user)
        {
            $this->user->setFirstname('mic');
            $this->user->setConfirm('1');
            $this->user->setValid('1');
            $this->user->setEmail('lol@lol.moid');
            $this->user->setPassword('lol');
            $this->user->setPhoto('azert');
        }

        public function testFirstName()
        {
            $this->assertEquals('mic',$this->user->getFirstname());
        }

        public function testFirstNameType()
        {
            $this->assertIsString($this->user->getFirstname());
        }

        public function testConfirm()
        {
            $this->assertEquals('1',$this->user->getConfirm());
        }

        public function testValid()
        {
            $this->assertEquals('1',$this->user->getValid());
        }

        public function testMailType()
        {
            $this->assertIsString($this->user->getEmail());
        }

        public function testMail()
        {
            $this->assertEquals('lol@lol.moid',$this->user->getEmail());
        }

        public function testFailFirstname()
        {
            $this->assertIsNotInt($this->user->getFirstname());
        }

        public function testId()
        {
            $this->assertEquals(null,$this->user->getID());
        }

        public function testPassword()
        {
            $this->assertEquals('lol',$this->user->getPassword());
        }

        public function testPhoto()
        {
            $this->assertEquals('azert',$this->user->getPhoto());
        }

    }