<?php


    namespace App\Tests\src\Entity;


    use App\Entity\Video;
    use PHPUnit\Framework\TestCase;

    class VideoTest extends TestCase
    {
        private $video;

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->video = new Video();
            $this->hydrate($this->video);
        }

        public function hydrate($video)
        {
            $this->video->setName('azert');
        }

        public function testName()
        {
            $this->assertEquals('azert',$this->video->getName());
        }

        public function testNameType()
        {
            $this->assertIsString($this->video->getName());
        }

        public function testId()
        {
            $this->assertEquals(null,$this->video->getId());
        }

        public function testDetail()
        {
            $this->assertEquals(null,$this->video->getDetail());
        }

    }