<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.N747g0D' shared service.

return $this->privates['.service_locator.N747g0D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'videoRepository' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService.php', true],
]);
