<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.meBJUHU' shared service.

return $this->privates['.service_locator.meBJUHU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'figure' => ['privates', '.errored..service_locator.meBJUHU.App\\Entity\\Figure', NULL, 'Cannot autowire service ".service_locator.meBJUHU": it references class "App\\Entity\\Figure" but no such service exists.'],
]);
