<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fLko.rf' shared service.

return $this->privates['.service_locator.fLko.rf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService.php', true],
    'figureRepository' => ['privates', 'App\\Repository\\FigureRepository', 'getFigureRepositoryService.php', true],
    'post' => ['privates', '.errored..service_locator.fLko.rf.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.fLko.rf": it references class "App\\Entity\\Post" but no such service exists.'],
    'videoRepository' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService.php', true],
]);
