<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\CustomEvent' shared autowired service.

include_once $this->targetDirs[3].'\\src\\EventListener\\CustomEvent.php';

return $this->privates['App\\EventListener\\CustomEvent'] = new \App\EventListener\CustomEvent(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->privates['App\\Repository\\UserRepository'] ?? $this->load('getUserRepositoryService.php')));
