<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.9yLvjYR.App\Entity\Figure' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Figure.php';

return $this->privates['.errored..service_locator.9yLvjYR.App\\Entity\\Figure'] = new \App\Entity\Figure();
