<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWG8sEbN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWG8sEbN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWG8sEbN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWG8sEbN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWG8sEbN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WG8sEbN',
    'container.build_id' => 'fbc88042',
    'container.build_time' => 1563799806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWG8sEbN');
