<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDKifeBb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDKifeBb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDKifeBb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDKifeBb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDKifeBb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DKifeBb',
    'container.build_id' => 'e6cc63a2',
    'container.build_time' => 1563269311,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDKifeBb');
